apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: sec1
    image: ubuntu:latest
    command: ["sleep", "3600"]   # 👈 keep container running
    env:
    - name: pass
      valueFrom:
        secretKeyRef:
          name: secret
          key: password
